apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 30090

